// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api // import "github.com/laik/minimal-cache/api"

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FSMCommand) Validate() error {
	return nil
}
func (this *UpdateMetadataRequest) Validate() error {
	return nil
}
func (this *UpdateMetadataResponse) Validate() error {
	return nil
}
func (this *ExecuteCommandRequest) Validate() error {
	return nil
}
func (this *ExecuteCommandResponse) Validate() error {
	return nil
}
func (this *AddToClusterRequest) Validate() error {
	return nil
}
func (this *AddToClusterResponse) Validate() error {
	return nil
}
func (this *RemoveClusterRequest) Validate() error {
	return nil
}
func (this *RemoveClusterResponse) Validate() error {
	return nil
}
func (this *MemeberRequest) Validate() error {
	return nil
}
func (this *RaftMemberInfo) Validate() error {
	return nil
}
func (this *MemberResponse) Validate() error {
	for _, item := range this.RaftNodes {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RaftNodes", err)
			}
		}
	}
	return nil
}
