// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api // import "github.com/laik/minimal-cache/api"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/mwitkow/go-proto-validators"

import github_com_laik_minimal_cache_raw "github.com/laik/minimal-cache/raw"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// FSMCommandType describes all available commands that FSM can apply.
type FSMCommandType int32

const (
	FSMApplyCommand  FSMCommandType = 0
	FSMApplyMetadata FSMCommandType = 1
)

var FSMCommandType_name = map[int32]string{
	0: "APPLY_COMMAND",
	1: "APPLY_METADATA",
}
var FSMCommandType_value = map[string]int32{
	"APPLY_COMMAND":  0,
	"APPLY_METADATA": 1,
}

func (x FSMCommandType) String() string {
	return proto.EnumName(FSMCommandType_name, int32(x))
}
func (FSMCommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{0}
}

// CommandExecutionReply describes all available replies.
type CommandExecutionReply int32

const (
	NilCommandReply    CommandExecutionReply = 0
	OkCommandReply     CommandExecutionReply = 1
	StringCommandReply CommandExecutionReply = 2
	SliceCommandReply  CommandExecutionReply = 3
	ErrCommandReply    CommandExecutionReply = 4
)

var CommandExecutionReply_name = map[int32]string{
	0: "NIL",
	1: "OK",
	2: "STRING",
	3: "SLICE",
	4: "ERR",
}
var CommandExecutionReply_value = map[string]int32{
	"NIL":    0,
	"OK":     1,
	"STRING": 2,
	"SLICE":  3,
	"ERR":    4,
}

func (x CommandExecutionReply) String() string {
	return proto.EnumName(CommandExecutionReply_name, int32(x))
}
func (CommandExecutionReply) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{1}
}

// FSMCommand is a FSM command.
type FSMCommand struct {
	Type                 FSMCommandType                        `protobuf:"varint,1,opt,name=type,proto3,enum=api.FSMCommandType" json:"type,omitempty"`
	Command              github_com_laik_minimal_cache_raw.Raw `protobuf:"bytes,2,opt,name=command,proto3,customtype=github.com/laik/minimal-cache/raw.Raw" json:"command"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *FSMCommand) Reset()         { *m = FSMCommand{} }
func (m *FSMCommand) String() string { return proto.CompactTextString(m) }
func (*FSMCommand) ProtoMessage()    {}
func (*FSMCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{0}
}
func (m *FSMCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSMCommand.Unmarshal(m, b)
}
func (m *FSMCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSMCommand.Marshal(b, m, deterministic)
}
func (dst *FSMCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSMCommand.Merge(dst, src)
}
func (m *FSMCommand) XXX_Size() int {
	return xxx_messageInfo_FSMCommand.Size(m)
}
func (m *FSMCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_FSMCommand.DiscardUnknown(m)
}

var xxx_messageInfo_FSMCommand proto.InternalMessageInfo

func (m *FSMCommand) GetType() FSMCommandType {
	if m != nil {
		return m.Type
	}
	return FSMApplyCommand
}

// UpdateMetadataRequest is used to update meta info in the raft FSM.
type UpdateMetadataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataRequest) Reset()         { *m = UpdateMetadataRequest{} }
func (m *UpdateMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataRequest) ProtoMessage()    {}
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{1}
}
func (m *UpdateMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataRequest.Merge(dst, src)
}
func (m *UpdateMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataRequest.Size(m)
}
func (m *UpdateMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataRequest proto.InternalMessageInfo

func (m *UpdateMetadataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateMetadataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// UpdateMetadataResponse is a response on the UpdateMetadataRequest.
type UpdateMetadataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataResponse) Reset()         { *m = UpdateMetadataResponse{} }
func (m *UpdateMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataResponse) ProtoMessage()    {}
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{2}
}
func (m *UpdateMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataResponse.Unmarshal(m, b)
}
func (m *UpdateMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataResponse.Merge(dst, src)
}
func (m *UpdateMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataResponse.Size(m)
}
func (m *UpdateMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataResponse proto.InternalMessageInfo

// ExecuteCommandRequest is a request to execute a command.
type ExecuteCommandRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteCommandRequest) Reset()         { *m = ExecuteCommandRequest{} }
func (m *ExecuteCommandRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteCommandRequest) ProtoMessage()    {}
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{3}
}
func (m *ExecuteCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteCommandRequest.Unmarshal(m, b)
}
func (m *ExecuteCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteCommandRequest.Marshal(b, m, deterministic)
}
func (dst *ExecuteCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteCommandRequest.Merge(dst, src)
}
func (m *ExecuteCommandRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteCommandRequest.Size(m)
}
func (m *ExecuteCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteCommandRequest proto.InternalMessageInfo

func (m *ExecuteCommandRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// ExecuteCommandResponse is a response on the ExecuteCommandRequest.
type ExecuteCommandResponse struct {
	Reply                CommandExecutionReply `protobuf:"varint,1,opt,name=reply,proto3,enum=api.CommandExecutionReply" json:"reply,omitempty"`
	Item                 string                `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Items                []string              `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExecuteCommandResponse) Reset()         { *m = ExecuteCommandResponse{} }
func (m *ExecuteCommandResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteCommandResponse) ProtoMessage()    {}
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{4}
}
func (m *ExecuteCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteCommandResponse.Unmarshal(m, b)
}
func (m *ExecuteCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteCommandResponse.Marshal(b, m, deterministic)
}
func (dst *ExecuteCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteCommandResponse.Merge(dst, src)
}
func (m *ExecuteCommandResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteCommandResponse.Size(m)
}
func (m *ExecuteCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteCommandResponse proto.InternalMessageInfo

func (m *ExecuteCommandResponse) GetReply() CommandExecutionReply {
	if m != nil {
		return m.Reply
	}
	return NilCommandReply
}

func (m *ExecuteCommandResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ExecuteCommandResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

// AddToClusterRequest is a request to add a new raft node to the cluster.
type AddToClusterRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToClusterRequest) Reset()         { *m = AddToClusterRequest{} }
func (m *AddToClusterRequest) String() string { return proto.CompactTextString(m) }
func (*AddToClusterRequest) ProtoMessage()    {}
func (*AddToClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{5}
}
func (m *AddToClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToClusterRequest.Unmarshal(m, b)
}
func (m *AddToClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToClusterRequest.Marshal(b, m, deterministic)
}
func (dst *AddToClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToClusterRequest.Merge(dst, src)
}
func (m *AddToClusterRequest) XXX_Size() int {
	return xxx_messageInfo_AddToClusterRequest.Size(m)
}
func (m *AddToClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToClusterRequest proto.InternalMessageInfo

func (m *AddToClusterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddToClusterRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// AddToClusterResponse is a reponse on the AddToClusterRequest.
type AddToClusterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToClusterResponse) Reset()         { *m = AddToClusterResponse{} }
func (m *AddToClusterResponse) String() string { return proto.CompactTextString(m) }
func (*AddToClusterResponse) ProtoMessage()    {}
func (*AddToClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_9373bc4f53f2d423, []int{6}
}
func (m *AddToClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToClusterResponse.Unmarshal(m, b)
}
func (m *AddToClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToClusterResponse.Marshal(b, m, deterministic)
}
func (dst *AddToClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToClusterResponse.Merge(dst, src)
}
func (m *AddToClusterResponse) XXX_Size() int {
	return xxx_messageInfo_AddToClusterResponse.Size(m)
}
func (m *AddToClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToClusterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FSMCommand)(nil), "api.FSMCommand")
	proto.RegisterType((*UpdateMetadataRequest)(nil), "api.UpdateMetadataRequest")
	proto.RegisterType((*UpdateMetadataResponse)(nil), "api.UpdateMetadataResponse")
	proto.RegisterType((*ExecuteCommandRequest)(nil), "api.ExecuteCommandRequest")
	proto.RegisterType((*ExecuteCommandResponse)(nil), "api.ExecuteCommandResponse")
	proto.RegisterType((*AddToClusterRequest)(nil), "api.AddToClusterRequest")
	proto.RegisterType((*AddToClusterResponse)(nil), "api.AddToClusterResponse")
	proto.RegisterEnum("api.FSMCommandType", FSMCommandType_name, FSMCommandType_value)
	proto.RegisterEnum("api.CommandExecutionReply", CommandExecutionReply_name, CommandExecutionReply_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MinimalCacheClient is the client API for MinimalCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinimalCacheClient interface {
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	AddToCluster(ctx context.Context, in *AddToClusterRequest, opts ...grpc.CallOption) (*AddToClusterResponse, error)
}

type minimalCacheClient struct {
	cc *grpc.ClientConn
}

func NewMinimalCacheClient(cc *grpc.ClientConn) MinimalCacheClient {
	return &minimalCacheClient{cc}
}

func (c *minimalCacheClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, "/api.MinimalCache/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minimalCacheClient) AddToCluster(ctx context.Context, in *AddToClusterRequest, opts ...grpc.CallOption) (*AddToClusterResponse, error) {
	out := new(AddToClusterResponse)
	err := c.cc.Invoke(ctx, "/api.MinimalCache/AddToCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinimalCacheServer is the server API for MinimalCache service.
type MinimalCacheServer interface {
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	AddToCluster(context.Context, *AddToClusterRequest) (*AddToClusterResponse, error)
}

func RegisterMinimalCacheServer(s *grpc.Server, srv MinimalCacheServer) {
	s.RegisterService(&_MinimalCache_serviceDesc, srv)
}

func _MinimalCache_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinimalCacheServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MinimalCache/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinimalCacheServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinimalCache_AddToCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinimalCacheServer).AddToCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MinimalCache/AddToCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinimalCacheServer).AddToCluster(ctx, req.(*AddToClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MinimalCache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MinimalCache",
	HandlerType: (*MinimalCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _MinimalCache_ExecuteCommand_Handler,
		},
		{
			MethodName: "AddToCluster",
			Handler:    _MinimalCache_AddToCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_9373bc4f53f2d423) }

var fileDescriptor_api_9373bc4f53f2d423 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x41, 0x6f, 0xd3, 0x48,
	0x14, 0xae, 0xe3, 0xa4, 0xab, 0x3e, 0x65, 0xb3, 0xee, 0xb4, 0xc9, 0x66, 0xbd, 0xd5, 0xd6, 0xb2,
	0xb4, 0xbb, 0x55, 0x44, 0xe2, 0xb6, 0x48, 0x48, 0x14, 0x24, 0xe4, 0xa6, 0x69, 0x55, 0xd1, 0xa4,
	0x95, 0x13, 0x0e, 0x20, 0x24, 0x34, 0xb1, 0x07, 0x77, 0x88, 0xe3, 0x31, 0xf6, 0xa4, 0x69, 0x2e,
	0x1c, 0x38, 0xa1, 0x1c, 0xe1, 0x9c, 0x13, 0x3f, 0x83, 0x3f, 0xc0, 0x11, 0x89, 0x1b, 0x87, 0x9e,
	0xf8, 0x21, 0xc8, 0xe3, 0xb8, 0x4d, 0xaa, 0x20, 0x4e, 0x7e, 0x2f, 0xdf, 0xf7, 0xbe, 0xf7, 0xcd,
	0x9b, 0x37, 0x81, 0x15, 0x1c, 0xd0, 0x5a, 0x10, 0x32, 0xce, 0x90, 0x8c, 0x03, 0xaa, 0x56, 0x5d,
	0xca, 0xcf, 0x07, 0xdd, 0x9a, 0xcd, 0xfa, 0x86, 0xcb, 0x5c, 0x66, 0x08, 0xac, 0x3b, 0x78, 0x29,
	0x32, 0x91, 0x88, 0x28, 0xa9, 0x51, 0x37, 0x5c, 0xc6, 0x5c, 0x8f, 0x18, 0x38, 0xa0, 0x06, 0xf6,
	0x7d, 0xc6, 0x31, 0xa7, 0xcc, 0x8f, 0xa6, 0xe8, 0x1d, 0xf1, 0xb1, 0xab, 0x2e, 0xf1, 0xab, 0xd1,
	0x10, 0xbb, 0x2e, 0x09, 0x0d, 0x16, 0x08, 0xc6, 0x02, 0xf6, 0xbd, 0x99, 0xd6, 0xfd, 0x21, 0xe5,
	0x3d, 0x36, 0x34, 0x5c, 0x56, 0x15, 0x60, 0xf5, 0x02, 0x7b, 0xd4, 0xc1, 0x9c, 0x85, 0x91, 0x71,
	0x1d, 0x26, 0x75, 0xfa, 0x1b, 0x80, 0xc3, 0x76, 0xb3, 0xce, 0xfa, 0x7d, 0xec, 0x3b, 0xe8, 0x7f,
	0xc8, 0xf2, 0x51, 0x40, 0xca, 0x92, 0x26, 0x6d, 0x15, 0x76, 0xd7, 0x6a, 0xf1, 0xf9, 0x6e, 0xe0,
	0xce, 0x28, 0x20, 0x96, 0x20, 0xa0, 0x23, 0xf8, 0xcd, 0x4e, 0x7e, 0x2c, 0x67, 0x34, 0x69, 0x2b,
	0xbf, 0x5f, 0xfd, 0x7c, 0xb5, 0xb9, 0xf4, 0xed, 0x6a, 0xf3, 0xdf, 0x19, 0x1f, 0x1e, 0xa6, 0x3d,
	0xa3, 0x4f, 0x7d, 0xda, 0xc7, 0x5e, 0xd5, 0xc6, 0xf6, 0x39, 0x31, 0x42, 0x3c, 0xac, 0x59, 0x78,
	0x68, 0xa5, 0xd5, 0xfa, 0x23, 0x28, 0x3e, 0x09, 0x1c, 0xcc, 0x49, 0x93, 0x70, 0xec, 0x60, 0x8e,
	0x2d, 0xf2, 0x7a, 0x40, 0x22, 0x8e, 0x14, 0x90, 0x7b, 0x64, 0x24, 0x9c, 0xac, 0x58, 0x71, 0x88,
	0xd6, 0x21, 0x77, 0x81, 0xbd, 0x01, 0x11, 0x1d, 0x57, 0xac, 0x24, 0xd1, 0xcb, 0x50, 0xba, 0x2d,
	0x10, 0x05, 0xcc, 0x8f, 0x88, 0xbe, 0x03, 0xc5, 0xc6, 0x25, 0xb1, 0x07, 0x9c, 0x4c, 0xfd, 0xa7,
	0xd2, 0xe5, 0x1b, 0xf3, 0x89, 0xfc, 0xb5, 0x1b, 0x0e, 0xa5, 0xdb, 0x25, 0x89, 0x18, 0xda, 0x86,
	0x5c, 0x48, 0x02, 0x6f, 0x34, 0x1d, 0x8d, 0x2a, 0x46, 0x33, 0x25, 0x25, 0x25, 0x94, 0xf9, 0x56,
	0xcc, 0xb0, 0x12, 0x22, 0x42, 0x90, 0xa5, 0x9c, 0xf4, 0xa7, 0x6e, 0x45, 0x1c, 0x1f, 0x21, 0xfe,
	0x46, 0x65, 0x59, 0x93, 0xe3, 0x23, 0x88, 0x44, 0xbf, 0x0f, 0x6b, 0xa6, 0xe3, 0x74, 0x58, 0xdd,
	0x1b, 0x44, 0x9c, 0x84, 0xa9, 0xcd, 0x02, 0x64, 0x68, 0xea, 0x30, 0x43, 0x9d, 0x58, 0x10, 0x3b,
	0x4e, 0x98, 0x0a, 0xc6, 0xb1, 0x5e, 0x82, 0xf5, 0xf9, 0xd2, 0xc4, 0x6e, 0xe5, 0x1c, 0x0a, 0xf3,
	0xf7, 0x86, 0xfe, 0x83, 0xdf, 0xcd, 0xb3, 0xb3, 0x93, 0xa7, 0x2f, 0xea, 0xa7, 0xcd, 0xa6, 0xd9,
	0x3a, 0x50, 0x96, 0xd4, 0xb5, 0xf1, 0x44, 0xfb, 0xe3, 0xb0, 0xdd, 0x34, 0x83, 0xc0, 0x1b, 0xa5,
	0x2b, 0xb0, 0x05, 0x85, 0x84, 0xd7, 0x6c, 0x74, 0xcc, 0x03, 0xb3, 0x63, 0x2a, 0x92, 0xba, 0x3e,
	0x9e, 0x68, 0x4a, 0x4a, 0x4c, 0xe7, 0xac, 0x66, 0xdf, 0x7d, 0xfc, 0x67, 0xa9, 0xf2, 0x49, 0x82,
	0xe2, 0xc2, 0x39, 0xa0, 0x0d, 0x90, 0x5b, 0xc7, 0x27, 0x69, 0x9f, 0x16, 0xf5, 0xae, 0x67, 0x1a,
	0xa3, 0x2a, 0x64, 0x4e, 0x1f, 0x2b, 0x92, 0x8a, 0xc6, 0x13, 0xad, 0x70, 0xda, 0x9b, 0xc3, 0x74,
	0x58, 0x6e, 0x77, 0xac, 0xe3, 0xd6, 0x91, 0x92, 0x51, 0x4b, 0xe3, 0x89, 0x86, 0xda, 0x3c, 0xa4,
	0xbe, 0x3b, 0xc7, 0xd1, 0x20, 0xd7, 0x3e, 0x39, 0xae, 0x37, 0x14, 0x59, 0x2d, 0x8e, 0x27, 0xda,
	0x6a, 0xdb, 0xa3, 0x36, 0x99, 0x63, 0x6c, 0x80, 0xdc, 0xb0, 0x2c, 0x25, 0x9b, 0xf4, 0x6f, 0x84,
	0xe1, 0x2c, 0x9a, 0xb8, 0xdf, 0xfd, 0x22, 0x41, 0xbe, 0x99, 0x6c, 0x68, 0x3d, 0x5e, 0x50, 0xd4,
	0x85, 0xc2, 0xfc, 0x06, 0xa0, 0xe4, 0xaa, 0x17, 0x6e, 0x92, 0xfa, 0xf7, 0x42, 0x6c, 0xba, 0x7f,
	0x7f, 0xbe, 0xfd, 0xfa, 0xfd, 0x43, 0x66, 0x55, 0xcf, 0x8b, 0x07, 0x7e, 0xb1, 0x63, 0x90, 0x4b,
	0x62, 0xef, 0x49, 0x15, 0xf4, 0x1c, 0xf2, 0xb3, 0x97, 0x86, 0xca, 0x42, 0x65, 0xc1, 0x0a, 0xa8,
	0x7f, 0x2d, 0x40, 0x7e, 0xa6, 0xfe, 0x8a, 0x51, 0x7f, 0x4f, 0xaa, 0xec, 0x3f, 0x7c, 0x6f, 0x22,
	0x94, 0xdb, 0x95, 0x77, 0x6a, 0xdb, 0x15, 0x29, 0x13, 0x2e, 0x43, 0xd6, 0x67, 0x3e, 0x79, 0xf6,
	0x8b, 0x87, 0x89, 0x03, 0xfa, 0x00, 0x07, 0xb4, 0xbb, 0x2c, 0xfe, 0x16, 0xee, 0xfe, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x2b, 0x57, 0xc1, 0x6a, 0xdb, 0x04, 0x00, 0x00,
}
